baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ananya Harsh Jha
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        # - name: Courses
        #   url: courses/
        #   weight: 2
        # - name: Data
        #   url: data/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Predoctoral Researcher on the AllenNLP team at AI2."
    author: Ananya Harsh Jha
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ananya Harsh Jha
          subtitle: "Hi! I am a [**Predoctoral Researcher**](https://allenai.org/predoctoral-young-investigators) on the
                    [**AllenNLP**](https://allenai.org/allennlp) team at [**AI2**](https://allenai.org/).
                    I have been fortunate enough to work with [**Iz Beltagy**](https://beltagy.net/) and [**Emma Strubell**](https://strubell.github.io/).
                    My research interests are efficient modeling, model compression, and retrieval-augmented models. <br />

                    <br />

                    Previously, I was a Research Engineer at [**PyTorch Lightning**](https://github.com/Lightning-AI/lightning).
                    I co-wrote [**TorchMetrics**](https://github.com/Lightning-AI/torchmetrics) with [**Teddy Koker**](https://teddykoker.com/)
                    and worked on [**stochastic-autoencoders**](https://arxiv.org/pdf/2107.12329.pdf) with [**Kyunghyun Cho**](https://www.kyunghyuncho.me/).
                    Even before that, I worked on [**cycle-VAEs**](https://openaccess.thecvf.com/content_ECCV_2018/papers/Ananya_Harsh_Jha_Disentangling_Factors_of_ECCV_2018_paper.pdf)
                    with [**Saket Anand**](https://faculty.iiitd.ac.in/~anands/)."
          imageUrl: "head_shot.jpg"
          imageWidth: 240
          imageHeight: 160
          imageTitle: Ananya Harsh Jha
          buttons:
            - name: Papers
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ananyaj@allenai.org
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=USRgM88AAAAJ
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/ananyahjha93
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/AnanyaHarsh

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ananya Harsh Jha"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
